In [1]:
from pandas import Series,DataFrame
import pandas as pd
obj=Series([9,8,7,3,4])
obj

0    9
1    8
2    7
3    3
4    4
dtype: int64

In [2]:
obj.values

array([9, 8, 7, 3, 4], dtype=int64)

In [3]:
obj.index

RangeIndex(start=0, stop=5, step=1)

In [4]:
obj.index=['a','b','c','d','e'] # index 可以进行重新设置
obj

a    9
b    8
c    7
d    3
e    4
dtype: int64

In [13]:
obj.index[0]='h' # 单个赋值是不可行的，只能整体赋值

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [11]:
# 通过index可以索引单个值
obj['a']

9

In [12]:
obj['a']=11
obj

a    11
b     8
c     7
d     3
e     4
dtype: int64

In [14]:
# series 的第二种创建方法---字典
obj2=Series({'a':1,'b':2,'c':3,'d':4})
obj2

a    1
b    2
c    3
d    4
dtype: int64

In [16]:
indexs=['b','c','d','f']
obj3=Series(obj2,index=indexs)
obj3           # 第三种创建方式---Series+index

b    2.0
c    3.0
d    4.0
f    NaN
dtype: float64

In [19]:
pd.isnull(obj3) # 检查是否有null值

b    False
c    False
d    False
f     True
dtype: bool

In [21]:
pd.notnull(obj3)  # 检查非null值

b     True
c     True
d     True
f    False
dtype: bool

In [22]:
# 自动补齐功能
obj2+obj3  # 由于obj3中f为nan,没有a，所以最终的值如下所示

a    NaN
b    4.0
c    6.0
d    8.0
f    NaN
dtype: float64

In [24]:
# Name----相当于R语言里面dataframe的行---不对，这里不能以R的DATAFRAME的思想来对PYTHON进行同样理解，R里面对DATAFRAME可以进行数字index,不一定在这里可以同理进行
# name 与后面的dataframe紧密联系
obj3.name='num'
obj3.index.name='names'
obj3

names
b    2.0
c    3.0
d    4.0
f    NaN
Name: num, dtype: float64

In [25]:
# 第一种创建dataframe的方法
data={'state':['ohin','ohin','ohin','nevada','nevada'],
     'year':[2000,2001,2002,2001,2002],
     'pop':[1.5,1.7,3.6,2.4,2.9]}
df1=DataFrame(data)
df1  # 注意这里的列排序是按照字母，大小来排列的，如要按某种序列，需要columns指定顺序

pop   state  year
0  1.5    ohin  2000
1  1.7    ohin  2001
2  3.6    ohin  2002
3  2.4  nevada  2001
4  2.9  nevada  2002

In [26]:
DataFrame(data,columns=['state','year','pop'])

state  year  pop
0    ohin  2000  1.5
1    ohin  2001  1.7
2    ohin  2002  3.6
3  nevada  2001  2.4
4  nevada  2002  2.9

In [34]:
df2=DataFrame(df1,columns=['state','year','pop','debt'],
              index=[1,2,4])
df2             # 不存在的columns和不存在的index将赋值为nan

state  year  pop  debt
1    ohin  2001  1.7   NaN
2    ohin  2002  3.6   NaN
4  nevada  2002  2.9   NaN

In [49]:
df2.set_index([[1,2,3]]) # 重设index ATTENTION,set_index[[],[]]需要传入list中包含list

state  year  pop  debt
1    ohin  2001  1.7   NaN
2    ohin  2002  3.6   NaN
3  nevada  2002  2.9   NaN

In [50]:
df2.set_index([[1,2,3],'state']) # 可以重设两个为index---array也可以

year  pop  debt
  state                  
1 ohin    2001  1.7   NaN
2 ohin    2002  3.6   NaN
3 nevada  2002  2.9   NaN

In [59]:
df1['state'] # 取出某一列，将其转化为series

0      ohin
1      ohin
2      ohin
3    nevada
4    nevada
Name: state, dtype: object

In [60]:
df1.state  #两种方式一样的

0      ohin
1      ohin
2      ohin
3    nevada
4    nevada
Name: state, dtype: object

In [73]:
df1.ix[3] # 加了ix 之后，行，列

pop         2.4
state    nevada
year       2001
Name: 3, dtype: object

In [74]:
df1.ix[3,1] 

'nevada'

In [75]:
df1.ix[3,'state'] # 同上面那种用法

'nevada'

In [77]:
df2.debt=1.5
df2   # 广播赋值

state  year  pop  debt
1    ohin  2001  1.7   1.5
2    ohin  2002  3.6   1.5
4  nevada  2002  2.9   1.5

In [79]:
import numpy as np
df2.debt=np.arange(3)
df2

state  year  pop  debt
1    ohin  2001  1.7     0
2    ohin  2002  3.6     1
4  nevada  2002  2.9     2

In [81]:
df1
val =Series([-1.2,-1.5,1.6],index=[1,2,3])
df1['debt']=val
df1

pop   state  year  debt
0  1.5    ohin  2000   NaN
1  1.7    ohin  2001  -1.2
2  3.6    ohin  2002  -1.5
3  2.4  nevada  2001   1.6
4  2.9  nevada  2002   NaN

In [82]:
df1['easten']=df1.state=='ohin'
df1

pop   state  year  debt  easten
0  1.5    ohin  2000   NaN    True
1  1.7    ohin  2001  -1.2    True
2  3.6    ohin  2002  -1.5    True
3  2.4  nevada  2001   1.6   False
4  2.9  nevada  2002   NaN   False

In [84]:
del df1['easten']  # 删除某列的唯一用法

In [85]:
df1

pop   state  year  debt
0  1.5    ohin  2000   NaN
1  1.7    ohin  2001  -1.2
2  3.6    ohin  2002  -1.5
3  2.4  nevada  2001   1.6
4  2.9  nevada  2002   NaN

In [87]:
# 双层字典建立 dataframe
df3=DataFrame(
{  'nevada':{2000:1.5,2001:2.3},
   'ohin':{1999:0.9,2000:2,2001:1.4}    
}
)
df3   # 这样建立，外层的key作为columns,内层的key作为index

nevada  ohin
1999     NaN   0.9
2000     1.5   2.0
2001     2.3   1.4

In [88]:
df3.T # 转置

1999  2000  2001
nevada   NaN   1.5   2.3
ohin     0.9   2.0   1.4

In [98]:
pdata={
    'one':df1['pop'][:-1],
    'two':df1['state'][:-1]
}
DataFrame(pdata)       # 还可以通过字典，value为Series

one     two
0  1.5    ohin
1  1.7    ohin
2  3.6    ohin
3  2.4  nevada

In [99]:
df3.index.name='year'
df3.columns.name='state'
df3  # 未行列名 命名

state  nevada  ohin
year               
1999      NaN   0.9
2000      1.5   2.0
2001      2.3   1.4

In [100]:
df3.values  # 他的values 是一个二维ndarray

array([[ nan,  0.9],
       [ 1.5,  2. ],
       [ 2.3,  1.4]])

In [105]:
'ohin' in df3.columns

True

In [107]:
1998 in df3.index # index 和columns都是一个set，可以用于判断是否存在某行或者某列


False

In [4]:
import pandas as np
from pandas import Series,DataFrame
df3=DataFrame(
{
    'nevada':{2000:1.5,2001:2.3},
    'ohin':{1999:0.9,2000:2,2001:1.4}    
}
)
df3

nevada  ohin
1999     NaN   0.9
2000     1.5   2.0
2001     2.3   1.4

In [9]:
df4=DataFrame(
{
    'nk':{1997:0.8,1998:2.1,1999:2.2,2000:2.8},
     'ak':{2000:2.4,2001:2.9}    
}

)
df4

ak   nk
1997  NaN  0.8
1998  NaN  2.1
1999  NaN  2.2
2000  2.4  2.8
2001  2.9  NaN

In [16]:
index1=df3.index

In [12]:
index2=df4.index

In [14]:
#一些index的运算

index1.append(index2) # 将index2全部添加到index1后面

Int64Index([1999, 2000, 2001, 1997, 1998, 1999, 2000, 2001], dtype='int64')

In [35]:
index1=df3.index
index1.difference(index2)

Int64Index([], dtype='int64')

In [28]:
index1.intersection(index2)

Int64Index([1999, 2000, 2001], dtype='int64')

In [36]:
index1.union(index2)

Int64Index([1997, 1998, 1999, 2000, 2001], dtype='int64')

In [37]:
index1.isin(index2) # 检查index1是否都在index2之中

array([ True,  True,  True], dtype=bool)

In [38]:
index1.delete(1) # 删除索引处的值

Int64Index([1999, 2001], dtype='int64')

In [44]:
index1=df3.index
index1.drop(2000)  # 删除传入的值

Int64Index([1999, 2001], dtype='int64')

In [46]:
index1.insert(1,2000)  #  在索引1处插入2000

Int64Index([1999, 2000, 2000, 2001], dtype='int64')

In [48]:
index1.is_monotonic  # 检查是否单调递增

True

In [50]:
index1.is_unique  # 检查是否唯一

True

In [52]:
index1.unique

<bound method Index.unique of Int64Index([1999, 2000, 2001], dtype='int64')>

In [54]:
# 一些重要的基本功能----reindex  
# 按照一定的方式来重新进行排序
# 对于reindex中的缺失需要进行补充
obj1=Series([4.5,7.2,-5.3,3.6],index=['d','b','a','c'])
obj1

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [55]:
obj2=obj1.reindex(['a','b','c','d','e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [56]:
obj2=obj1.reindex(['a','b','c','d','e'],fill_value=0)
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

In [58]:
obj3=Series(['blue','purple','yellow'],index=[0,2,4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [59]:
obj4=obj3.reindex(range(6),method='ffill')  # 向前填充值---填充nan
obj4

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [61]:
obj4=obj3.reindex(range(6),method='pad') # 向前搬运值
obj4

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [62]:
obj4=obj3.reindex(range(6),method='bfill') # 向后填充值 
obj4

0      blue
1    purple
2    purple
3    yellow
4    yellow
5       NaN
dtype: object

In [63]:
import numpy as np
df5=DataFrame( np.arange(9).reshape((3,3)),index=['a','c','d'],
              columns=['ohin','texas','california']
)
df5

ohin  texas  california
a     0      1           2
c     3      4           5
d     6      7           8

In [65]:
states=['ohin','utah','texas']
df5.reindex(columns=states)

ohin  utah  texas
a     0   NaN      1
c     3   NaN      4
d     6   NaN      7

In [68]:
df5.reindex(index=['a','b','c','d'],method='ffill') # 只能按axis=0来进行填充，不能按axis=1来填充

ohin  texas  california
a     0      1           2
b     0      1           2
c     3      4           5
d     6      7           8

In [76]:
obj5=Series(np.arange(5),index=['a','b','c','d','e'])
obj5.drop('a')

a    0
b    1
c    2
d    3
e    4
dtype: int32

In [78]:
obj5.drop(['a','d'])

b    1
c    2
e    4
dtype: int32

In [82]:
data=DataFrame(np.arange(16).reshape(4,4),index=['ohin','colorado','utah','new york'],
              columns=['one','two','three','four']
              )
data

one  two  three  four
ohin        0    1      2     3
colorado    4    5      6     7
utah        8    9     10    11
new york   12   13     14    15

In [84]:
data.drop(['two','four'],axis=1)

one  three
ohin        0      2
colorado    4      6
utah        8     10
new york   12     14

In [85]:
data.drop(['ohin','utah'],axis=0)

one  two  three  four
colorado    4    5      6     7
new york   12   13     14    15

In [87]:
## 注意
obj6=Series(np.arange(5),index=['a','b','c','d','e'])
obj6

a    0
b    1
c    2
d    3
e    4
dtype: int32

In [89]:
obj6['a':'d']  # index索引这个是前闭后闭

a    0
b    1
c    2
d    3
dtype: int32

In [90]:
obj6[:3]  #  数字索引是前闭后开

a    0
b    1
c    2
dtype: int32

In [92]:
data['two'] # DataFrame索引方式---只能用于columns这种方式

ohin         1
colorado     5
utah         9
new york    13
Name: two, dtype: int32

In [99]:
data.ix['utah',['two','one']]

two    9
one    8
Name: utah, dtype: int32

In [100]:
data.ix[['ohin','utah'],[3,0,1]]

four  one  two
ohin     3    0    1
utah    11    8    9

In [105]:
data.xs('ohin')

one      0
two      1
three    2
four     3
Name: ohin, dtype: int32

In [110]:
data.get_value('ohin','two')

1

In [111]:
data.set_value('ohin','two',3)

one  two  three  four
ohin        0    3      2     3
colorado    4    5      6     7
utah        8    9     10    11
new york   12   13     14    15

In [115]:
data.iloc[:,2]  # 如果纯数字索引推荐使用iloc

ohin         2
colorado     6
utah        10
new york    14
Name: three, dtype: int32

In [119]:
data.loc['ohin']  # loc是纯label来进行索引，单个表示行

one      0
two      3
three    2
four     3
Name: ohin, dtype: int32

In [120]:
data.ix['ohin',[1,2]] # ix可以混合索引

two      3
three    2
Name: ohin, dtype: int32

In [125]:
# data.iloc['ohin',:2]  错误不能使用label
data.iloc[2,0:2]

one    8
two    9
Name: utah, dtype: int32

In [126]:
# data.loc[2,['two','one']] 不能使用数字
data.loc['ohin','one':'four']

one      0
two      3
three    2
four     3
Name: ohin, dtype: int32

In [139]:
s1=Series([7.3,-2.5,3.4,1.5],index=['a','b','c','d'])
s2=Series([2.1,3.4,-2.3,9.8],index=['a','c','f','h'])
s1+s2  # 自动赋值为NULL

a    9.4
b    NaN
c    6.8
d    NaN
f    NaN
h    NaN
dtype: float64

In [2]:
import numpy as np
df1=DataFrame(
    np.arange(12).reshape((3,4)),columns=list('bcde'),index=list('opq')
)
df2=DataFrame(
    np.arange(9).reshape((3,3)),columns=list('def'),index=list('opq')
)
df1+df2  # 自动扩展，为null赋值为null

b   c   d   e   f
o NaN NaN   2   4 NaN
p NaN NaN   9  11 NaN
q NaN NaN  16  18 NaN

In [3]:
df1.add(df2,fill_value=0)   # 如果改位置不是一一对应，就将有的补上

b    c   d   e    f
o  0.0  1.0   2   4  2.0
p  4.0  5.0   9  11  5.0
q  8.0  9.0  16  18  8.0

In [11]:
df1-df1.iloc[0]

b  c  d  e
o  0  0  0  0
p  4  4  4  4
q  8  8  8  8

In [15]:
series1=Series(df1.iloc[0],index=list('abcdg'))
series1
df1-series1

a    b    c    d   e   g
o NaN  0.0  0.0  0.0 NaN NaN
p NaN  4.0  4.0  4.0 NaN NaN
q NaN  8.0  8.0  8.0 NaN NaN

In [17]:
series2=Series(df1['b'])
df1.sub(series2,axis=0)

b  c  d  e
o  0  1  2  3
p  0  1  2  3
q  0  1  2  3

In [21]:
f = lambda x: x.max()-x.min()
df1.apply(f,axis=1)    # apply 是针对行列来进行的

o    3
p    3
q    3
dtype: int64

In [23]:
f = lambda x : '%.3f'%x
df1.applymap(f)      # applymap是针对元素级的

b      c       d       e
o  0.000  1.000   2.000   3.000
p  4.000  5.000   6.000   7.000
q  8.000  9.000  10.000  11.000

In [25]:
df1['b'].map(f)  # map 是Series的元素操作方法

o    0.000
p    4.000
q    8.000
Name: b, dtype: object